{% set name = "02-id-six-collection" %}
{% set year = "2019" %}
{% set cycle = "3" %}
{% set version = "0" %}

package:
  name: {{ name | lower }}
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  skip: True  # [py<36]
  number: 0

requirements:
  host:
    - python
  run:
    - python
    - sixtools >=0.0.2

test:
  imports:
    - rixs
    - sixtools

about:
  home: https://github.com/NSLS-II-SIX
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Collection metapackage for SIX beamline
